[licenses]
# ensure all dependencies have licenses
unlicensed = "deny"

allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Zlib",
    "WTFPL",
    "Unicode-DFS-2016",
]

[bans]
# disable duplicate crates
multiple-versions = "deny"

[advisories]
# deny crates with some problems...
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"
